service: ri-watcher
custom: ${file(./setting.yml)}

provider:
  name: aws
  runtime: nodejs14.x
  profile: ${file(./setting.yml):PROFILE}
  environment:
    SLACK_WEBHOOK_URL: ${file(./setting.yml):SLACK_WEBHOOK_URL}

  stage: prod
  region: ${file(./setting.yml):REGION}

functions:
  RIWatcher:
    handler: handler.RIWatcher
    events:
     - schedule: ${file(./setting.yml):SCHEDULE}